nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - server1
    - server2
    - server3
server1:
  build: ./
  ports:
    - "8080"
server2:
  build: ./
  ports:
    - "8080"
server3:
  build: ./
  ports:
    - "8080"
